# Generated by Django 2.2.16 on 2021-09-29 15:36

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210923_2018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_together',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_following',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_together'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='self_following'),
        ),
    ]
